# Generated by Django 5.1.6 on 2025-03-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('image1', models.ImageField(upload_to='gallery_images/')),
                ('image2', models.ImageField(upload_to='gallery_images/')),
                ('image3', models.ImageField(upload_to='gallery_images/')),
                ('image4', models.ImageField(upload_to='gallery_images/')),
                ('image5', models.ImageField(upload_to='gallery_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.brand')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.gender')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.type')),
            ],
        ),
    ]
