# Generated by Django 5.1.7 on 2025-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_alter_product_brand_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Analogue', 'Analogue'), ('Digital', 'Digital'), ('Analogue/Digital', 'Analogue/Digital')], max_length=20, null=True),
        ),
    ]
