# Generated by Django 5.1.7 on 2025-03-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
